# shellcheck disable=SC2148
FROM opensuse/tumbleweed@sha256:21195432c141fd2ad48520df0f58ba4410b6a0d09989395623acaedfbdccf14e

RUN zypper refresh && \
    zypper addrepo https://download.opensuse.org/repositories/openSUSE:Tools/openSUSE_Tumbleweed/openSUSE:Tools.repo && \
    zypper --gpg-auto-import-keys refresh && \
    zypper install -y osc build git curl wget && \
    zypper clean -a

WORKDIR /workspace

CMD ["/bin/bash"]